// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ozowebapp.Models;

namespace ozowebapp.Migrations
{
    [DbContext(typeof(ConnectionStringClass))]
    partial class ConnectionStringClassModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ozowebapp.Models.DjelatnikClass", b =>
                {
                    b.Property<int>("DjelatnikClassID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Datum_rodjenja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ZanimanjeClassID")
                        .HasColumnType("int");

                    b.HasKey("DjelatnikClassID");

                    b.HasIndex("ZanimanjeClassID");

                    b.ToTable("Djelatnik");
                });

            modelBuilder.Entity("ozowebapp.Models.OpremaClass", b =>
                {
                    b.Property<int>("OpremaClassID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double?>("Cijena")
                        .HasColumnType("float");

                    b.Property<DateTime?>("Datum_proizvodnje")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Duljina_Koristenja_u_h")
                        .HasColumnType("float");

                    b.Property<int?>("Kolicina")
                        .HasColumnType("int");

                    b.Property<string>("Lokacija")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OpremaClassID");

                    b.ToTable("Oprema");
                });

            modelBuilder.Entity("ozowebapp.Models.ZanimanjeClass", b =>
                {
                    b.Property<int>("ZanimanjeClassID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Satnica")
                        .HasColumnType("float");

                    b.HasKey("ZanimanjeClassID");

                    b.ToTable("Zanimanje");
                });

            modelBuilder.Entity("ozowebapp.Models.DjelatnikClass", b =>
                {
                    b.HasOne("ozowebapp.Models.ZanimanjeClass", "ZanimanjeClass")
                        .WithMany("Djelatnici")
                        .HasForeignKey("ZanimanjeClassID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
